# Generated by Django 5.1.3 on 2024-11-21 05:47

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[users.validators.check_phone_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('C', 'COMMON-USER'), ('A', 'STADIONADMIN'), ('S', 'SUPERUSER')], default='C', max_length=20),
        ),
    ]
