# Generated by Django 5.1.3 on 2024-12-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_date_of_birth_user_middle_name_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
