# Generated by Django 5.1.3 on 2024-12-27 04:27

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_date_of_birth_remove_user_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[users.validators.check_phone_validator]),
        ),
    ]
