# Generated by Django 5.1.3 on 2024-11-13 05:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Stadion nomi')),
                ('description', models.TextField(verbose_name='Stadion haqida')),
                ('price', models.FloatField(verbose_name='Stadion narxi')),
                ('photo', models.ImageField(blank=True, help_text='Bu saytda asosiy rasm sifatida turadi', null=True, upload_to='stadion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png'])], verbose_name='Asosiy rasm')),
                ('start_time', models.TimeField(blank=True, help_text='Stadion boshlanish vaqti', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Stadion tugash vaqti', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('kiyinish_xonasi', models.BooleanField()),
                ('dush', models.BooleanField()),
                ('yoritish', models.BooleanField()),
                ('parkofka', models.BooleanField()),
                ('forma', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stadion',
                'verbose_name_plural': 'Stadionlar',
                'db_table': 'stadion',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stadion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png'])])),
                ('stadion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stadion.stadion')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'db_table': 'image',
            },
        ),
    ]
