# Generated by Django 5.1.3 on 2024-11-13 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stadion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='stadion',
            name='photo',
            field=models.ImageField(blank=True, help_text='Bu saytda asosiy rasm sifatida turadi', null=True, upload_to='stadion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Asosiy rasm'),
        ),
    ]
