# Generated by Django 5.1.3 on 2024-11-13 10:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0002_alter_images_image_alter_stadion_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StadionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rank', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('stadion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadionreviews', to='stadion.stadion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stadion sharhi',
                'verbose_name_plural': 'Stadion sharhlari',
                'db_table': 'stadion_review',
            },
        ),
    ]
