# Generated by Django 5.1.3 on 2024-12-10 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0003_stadion_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stadion',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_for_stadium'),
        ),
    ]
