# Generated by Django 5.1.3 on 2024-11-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0004_stadionreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadion',
            name='dush',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stadion',
            name='forma',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stadion',
            name='kiyinish_xonasi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stadion',
            name='parkofka',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stadion',
            name='yoritish',
            field=models.BooleanField(default=False),
        ),
    ]
