# Generated by Django 5.1.3 on 2024-12-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0004_stadion_unique_user_for_stadium'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stadion',
            name='unique_user_for_stadium',
        ),
    ]
