# Generated by Django 5.1.3 on 2024-12-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0005_remove_stadion_unique_user_for_stadium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadionreview',
            name='rank',
        ),
    ]
