# Generated by Django 5.1.3 on 2025-01-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0008_remove_stadion_end_time_remove_stadion_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stadionprice',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelTable(
            name='stadionprice',
            table='price',
        ),
    ]
