# Generated by Django 5.1.3 on 2025-01-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0009_alter_stadionprice_options_alter_stadionprice_table'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stadionprice',
            constraint=models.UniqueConstraint(fields=('stadion', 'time'), name='unique_price'),
        ),
    ]
