# Generated by Django 5.1.3 on 2025-02-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0011_stadion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadion',
            name='tishli_oyoqkiyim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stadion',
            name='usti_ochiq_yopiq',
            field=models.BooleanField(default=False),
        ),
    ]
