# Generated by Django 5.1.3 on 2025-02-08 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0012_stadion_tishli_oyoqkiyim_stadion_usti_ochiq_yopiq'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadion',
            name='tuman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.tuman'),
        ),
        migrations.AddField(
            model_name='stadion',
            name='viloyat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.viloyat'),
        ),
    ]
