# Generated by Django 5.1.3 on 2025-02-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0013_stadion_tuman_stadion_viloyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
