# Generated by Django 5.1.3 on 2025-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0014_stadion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadion',
            name='end_time',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='stadion',
            name='start_time',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
