# Generated by Django 5.1.3 on 2025-04-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0015_stadion_end_time_stadion_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadionprice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
