# Generated by Django 5.1.3 on 2025-04-12 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0016_stadionprice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadionreview',
            name='cover_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stadionreview',
            name='employee_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stadionreview',
            name='infrastructure_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stadionreview',
            name='is_anonym',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stadionreview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 5, 12, 9, 822003, tzinfo=datetime.timezone.utc)),
        ),
    ]
