# Generated by Django 5.1.3 on 2025-04-12 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0017_stadionreview_cover_rank_stadionreview_employee_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadionreview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 5, 30, 9, 429112, tzinfo=datetime.timezone.utc)),
        ),
    ]
