# Generated by Django 5.1.3 on 2025-04-12 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadion', '0018_alter_stadionreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadionreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
