# Generated by Django 5.1.3 on 2024-12-20 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('stadion', '0005_remove_stadion_unique_user_for_stadium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likedstadion',
            constraint=models.UniqueConstraint(fields=('user', 'stadion'), name='unique_liked_stadion'),
        ),
    ]
