# Generated by Django 5.1.3 on 2024-12-23 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_likedstadion_unique_liked_stadion'),
        ('stadion', '0005_remove_stadion_unique_user_for_stadium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Starts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stadion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StadionStarts', to='stadion.stadion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserStarts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Start',
                'verbose_name_plural': 'Starts',
                'db_table': 'starts',
            },
        ),
    ]
