# Generated by Django 5.1.3 on 2025-02-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_viloyat_tuman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tuman',
        ),
        migrations.DeleteModel(
            name='Viloyat',
        ),
    ]
