# Generated by Django 5.1.3 on 2025-04-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_delete_tuman_delete_viloyat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Starts',
        ),
    ]
