# Generated by Django 5.1.3 on 2024-11-18 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadion', '0002_rename_created_time_stadion_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BronStadion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('0', '00.00-01.00'), ('1', '01.00-02.00'), ('2', '02.00-03.00'), ('3', '03.00-04.00'), ('4', '04.00-05.00'), ('5', '05.00-06.00'), ('6', '06.00-07.00'), ('7', '07.00-08.00'), ('8', '08.00-09.00'), ('9', '09.00-10.00'), ('10', '10.00-11.00'), ('11', '11.00-12.00'), ('12', '12.00-13.00'), ('13', '13.00-14.00'), ('14', '14.00-15.00'), ('15', '15.00-16.00'), ('16', '16.00-17.00'), ('17', '17.00-18.00'), ('18', '18.00-19.00'), ('19', '19.00-20.00'), ('20', '20.00-21.00'), ('21', '21.00-22.00'), ('22', '22.00-23.00'), ('23', '23.00-00.00')], max_length=20)),
                ('date', models.DateField()),
                ('is_actice', models.BooleanField(default=False)),
                ('stadion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stadion_bronorders', to='stadion.stadion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bronorders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bron stadion',
                'verbose_name_plural': 'Bron stadionlar',
                'db_table': 'bronstadion',
            },
        ),
    ]
