# Generated by Django 5.1.3 on 2024-11-19 04:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_is_actice_bronstadion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronstadion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bronstadion',
            name='status',
            field=models.CharField(choices=[('TASDIQLANGAN', 'TASDIQLANGAN'), ('TASDIQLANMAGAN', 'TASDIQLANMAGAN')], default='TASDIQLANMAGAN', max_length=20),
        ),
    ]
