# Generated by Django 5.1.3 on 2024-12-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_bronstadion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronstadion',
            name='status',
            field=models.CharField(choices=[('K', 'KUTILMOQDA'), ('T', 'TASDIQLANGAN'), ('B', 'BEKOR_QILINGAN')], default='K', max_length=20),
        ),
    ]
