# Generated by Django 5.1.3 on 2024-12-11 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_bronstadion_unique_bron_stadion'),
        ('stadion', '0004_stadion_unique_user_for_stadium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bronstadion',
            name='unique_bron_stadion',
        ),
        migrations.AddConstraint(
            model_name='bronstadion',
            constraint=models.UniqueConstraint(fields=('time', 'date', 'user'), name='unique_bron_stadion'),
        ),
    ]
