# Generated by Django 5.1.3 on 2024-12-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_bronstadion_unique_bron_stadion_and_more'),
        ('stadion', '0006_remove_stadionreview_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronstadion',
            name='stadion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stadion_bronorders', to='stadion.stadion'),
        ),
    ]
