# Generated by Django 5.1.3 on 2025-01-28 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_bronstadion_user'),
        ('stadion', '0011_stadion_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bronstadion',
            name='unique_bron_stadion',
        ),
        migrations.AddConstraint(
            model_name='bronstadion',
            constraint=models.UniqueConstraint(fields=('time', 'date', 'user', 'stadion'), name='unique_bron_stadion'),
        ),
    ]
