# Generated by Django 5.1.3 on 2025-02-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_bronstadion_unique_bron_stadion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronstadion',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
