# Generated by Django 5.1.3 on 2025-04-12 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_bronstadion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronstadion',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bronstadion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 5, 30, 9, 430065, tzinfo=datetime.timezone.utc)),
        ),
    ]
