# Generated by Django 5.1.3 on 2025-04-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_bronstadion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronstadion',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
